name = "pms-af-garden"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "pms-af-garden-db"
database_id = "7cd11f48-7305-473d-a6f2-b73a98cd808e"   # replace after: wrangler d1 create pms-af-garden-db

[vars]
JWT_SECRET = "CHANGE_THIS_IN_PRODUCTION_SECRET_KEY_MIN_32_CHARS"
RESEND_API_KEY = "re_XXXXXXXX"
APP_URL = "https://your-domain.pages.dev"
RECEIPT_EMAIL_FROM = "noreply@afgarden.com"

# For local dev
[dev]
port = 8788
